/// Integration tests against pre-serialised domain JSON files.
///
/// JSON files live in `planner/test_domains/` and are generated by the full
/// pipeline (pandaPIparser → pandaPIgrounder → htn_parser.py).
///
#[cfg(test)]
mod tests {
    use super::super::run;
    use super::super::TiebreakerKind;
    use crate::domain_description::read_json_domain;
    use crate::search::{HeuristicType, SearchResult};


    fn check_fond(json_path: &str, heuristic: HeuristicType) {
        let problem = read_json_domain(json_path);
        let (result, _stats) = run(&problem, heuristic, TiebreakerKind::Combined);
        match result {
            SearchResult::Success(policy) => {
                assert!(
                    policy.success_probability >= 1.0 - 1e-9,
                    "{}: expected strong plan (prob=1.0), got prob={:.9}",
                    json_path,
                    policy.success_probability
                );
            }
            SearchResult::NoSolution => {
                panic!(
                    "{}: expected a strong plan to exist, got NoSolution",
                    json_path
                );
            }
        }
    }

    #[test]
    fn fond_lights_01() {
        check_fond("test_domains/fond_lights_01.json", HeuristicType::HFF);
        check_fond("test_domains/fond_lights_01.json", HeuristicType::HAdd);
    }

    #[test]
    fn fond_lights_02() {
        check_fond("test_domains/fond_lights_02.json", HeuristicType::HFF);
        check_fond("test_domains/fond_lights_02.json", HeuristicType::HAdd);
    }

    #[test]
    fn fond_metro_01() {
        check_fond("test_domains/fond_metro_01.json", HeuristicType::HFF);
    }

    #[test]
    fn fond_lights_01_lmcut() {
        check_fond("test_domains/fond_lights_01.json", HeuristicType::HLMCut);
    }

    #[test]
    fn fond_lights_02_lmcut() {
        check_fond("test_domains/fond_lights_02.json", HeuristicType::HLMCut);
    }
}
